### PR TITLE
Prevent inlining for GHCJS

### PR DESCRIPTION
**Pull request by dfithian**
Can't tell if I should add a CPP pragma for this, or just merge it into master.

@Dridus @asariley

### CODE REVIEW

**Comment by Dridus** [comment]
I think we want a CPP guard on it so the original performance is maintained in the non-GHCJS case

**Comment by dfithian** [comment]
Okay, done

**Comment by Dridus** [comment]
you can remove the flag and such by using `#ifdef ghcjs_HOST_OS` instead, I think

**Comment by dfithian** [comment]
:bow:

**Pull request merged**
